### ISSUE TITLE
virtualenv is needed to be able to make venv

### ISSUE THREAD

**Issue by TCHdvlp** [FabienArcellier/blueprint-webapp-flask#1]
Hey Fabien, maybe you should add a line in the readme about the installation of virtualenv ;)

blueprint-webapp-flask ->virtualenv venv -p python3
Le programme « virtualenv » n'est pas encore installé. Vous pouvez l'installer en tapant :
sudo apt install virtualenv

**Comment by FabienArcellier** [comment]
I have added a section about System requirement in `README` when I have switched from ``virtualenv`` to ``pipenv``. There are more than one option than one to setup those tools. 

It depends from the OS. I have choose to refer to their official documentation.
